### ISSUE TITLE
Evaluate image layer caching on GitHub Actions

### ISSUE THREAD

**Issue by rbreslow** [d3b-center/image-deid-etl#49]
I've experimented with the following changes in the `docker-compose.ci.yml` file in an attempt to export image layers to the GitHub Actions cache:

```yaml
services:
  image-deid-etl:
    image: image-deid-etl:${GIT_COMMIT:-latest}
    build:
      context: ./src/image_deid_etl
      cache_from: 
        - type=gha
      cache_to: 
        - type=gha,mode=max
```

(https://github.com/moby/buildkit#github-actions-cache-experimental)

Cache export is only available for the `docker-container` driver. However, when we create a new builder instance with the `docker-container` driver, it doesn't seem like Docker Compose uses it:

```yaml
- uses: docker/setup-buildx-action@v2
  id: buildx
  with:
      driver: docker-container
      install: true

# Make BuildKit aware of GitHub Actions.
# https://github.com/moby/buildkit/tree/master#github-actions-cache-experimental
- uses: crazy-max/ghaction-github-runtime@v2
```

<img width="855" alt="image" src="https://user-images.githubusercontent.com/1774125/175315494-d4e77336-74a6-4d32-be08-c21048a1f56c.png">

It looks like other folks have hit this in similar circumstances:
- https://github.com/docker/compose/issues/8531
- https://github.com/docker/compose/pull/9466

We shouldn't let this get in the way of CI setup since build times are < 2 minutes. However, we should reevaluate once there is progress on the pull request I mentioned because it'd be great to have an implementation of image layer caching on GitHub Actions, configured via Docker Compose.
